spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customers_db
    username: bnaqica
    password: password123
  jpa:
    show-sql: true
server:
  port: 2001
customers:
  baseUrl: http://dev.fakeonlinestore.com/
  customerUrl: customer/
  version: v3/
  timeout: 10